### ISSUE TITLE
截图问题

### ISSUE THREAD

**Issue by qiantao94** [uglyer/wechat_jump_ai_kotlin#3]
有时候会在方块没落稳就截图了
![_124](https://user-images.githubusercontent.com/16660255/34454251-561dba1c-eda2-11e7-929e-b41ac9c2e240.png)

**Comment by uglyer** [comment]
可以修改一下定时器的时间
https://github.com/uglyer/wechat_jump_ai_kotlin/blob/master/src/App/Main.kt
56 行，两个5000改的更长一些就可以了。

**Comment by uglyer** [comment]
6fe7b8c 加入定时器的参数设置
