### ISSUE TITLE
小米5不自动跳

### ISSUE THREAD

**Issue by skylarklxlong** [uglyer/wechat_jump_ai_kotlin#7]
你好！使用了您的代码后小人并不会自动跳，使用手机为小米5，log如下：
bgColor R:214 G:218 B:229
color.red:21 G:25 B:63 a:255
endH2:611
color.red:92 G:104 B:92 a:255
endH = (endH2 - endH) / 2:449 = (611 - 449) / 2
Complated.
distance:323
bgColor R:214 G:218 B:229
color.red:21 G:25 B:63 a:255
endH2:611
color.red:92 G:104 B:92 a:255
endH = (endH2 - endH) / 2:449 = (611 - 449) / 2
Complated.
distance:323
请问这是为何？谢谢

**Comment by skylarklxlong** [comment]
找到解决方法了，小米5需要打开usb模拟点击，现在可以正常运行了，但是每次跳20次左右就不行了

**Comment by uglyer** [comment]
可以适当调整移动系数试一下，如果点识别准确但是跳的位置不准确多半是这里的问题。

**Comment by skylarklxlong** [comment]
@uglyer 嗯好的，谢谢
